name: Test Workflow

on:
  push:
    branches:
      - 'master'
jobs:
  test-print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print
        run: echo "Hello, World!"